openapi: 3.0.0
info:
  title: XSS Test API
  version: 1.0.0
  description: API to test reflected/stored XSS payloads in comments

paths:
  /comments:
    post:
      summary: Submit a comment (with potential XSS)
      tags:
        - XSS Testing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentRequest'
      responses:
        '200':
          description: Comment stored
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommentResponse'

components:
  schemas:
    CommentRequest:
      type: object
      required:
        - content
      properties:
        content:
          type: string
          example: "<script>alert('XSS')</script>"
    CommentResponse:
      type: object
      properties:
        id:
          type: integer
          example: 123
        content:
          type: string
          example: "<script>alert('XSS')</script>"

servers:
  - url: https://xss.pentest-lab.local
